steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: 'git-function'
    
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['test']
    dir: 'git-function'
    
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'cicd-function'
      - '--trigger-http'
      - '--runtime=nodejs16'
      - '--entry-point=helloFromGit'
      - '--region=<YOUR_REGION>'
      - '--service-account=756138551924@cloudbuild.gserviceaccount.com'
      - '--project=students-api-db-427606'
    dir: 'git-function'
    env:
      - 'CLOUD_LOGGING_ONLY=true'
  


